Pick up SF4 translations location
zicht/z-plugin-messages pull request #2
Opened 2020-08-19 06:53 UTC by erik-zicht

2020-08-19 08:18 UTC, erik-zicht commented
:biohazard: :exploding_head: @patrick-zicht hiervoor moeten ook de build-images worden geupdate

2020-08-20 07:46 UTC, 7ochem commented
> Enige probleem is dat dit faalt als er geen `translations` folder is... 
> 
> ```shell
> While resolving value tasks.messages.load_files 
> -> Command 'cd /.../public_html/;
> find vendor/zicht translations src -type f -name "*.??.yml" -exec php /home/.../app/console --env=staging    --overwrite-import zicht:messages:load '{}' +' failed with exit code 1 [UnexpectedValueException] 
> ```
> 
> Hebben we zoiets nodig https://serverfault.com/questions/225798/can-i-make-find-return-non-0-when-no-matching-files-are-found ?

De link waarnaar je refereert gaat om een exit code, niet of de doel directory uberhaupt bestaat. Misschien het lijstje met dirs in een variabele zetten. Maar dat kan dan weer niet in z bash commands. Of in een variabele in Z, dus in alle Sf4 projecten die setting aanvullen.

2020-08-20 07:53 UTC, boudewijn-zicht requested changes
Dat `translations` dir soms niet bestaat moet anders opgelost worden, bijvoorbeeld door bash script:

```bash
TRANSLATION_DIRS=''
for DIR in "vendor/zicht" "src" "translations"; do
 if [[ -d "$DIR" ]]; then
   TRANSLATION_DIRS="$TRANSLATION_DIRS $DIR"
 fi
done
```

2020-08-20 07:53 UTC, boudewijn-zicht commented on messages/z.yml
> +          find vendor/zicht translations src -type f -name "*.??.yml" -exec $(defaults("php_bin", target_env, "php")) $(envs[target_env].root)$(symfony.console) --env=$(target_env) $(VERBOSE ? "--ver
Voelt handiger als de `translations` na de `src` staat.  De laatste overschrijft namelijk de waarde van de eerdere... en ik denk dat het logischer is dat `translations` prio heeft over wat er in `src` zou staan

2020-08-20 07:57 UTC, erik-zicht commented on messages/z.yml
> +          find vendor/zicht translations src -type f -name "*.??.yml" -exec $(defaults("php_bin", target_env, "php")) $(envs[target_env].root)$(symfony.console) --env=$(target_env) $(VERBOSE ? "--ver
In een SF4 project staan er geen translations meer in de `src`, die staan alleen nog in `translations`.
Door ze allebei te hebben ben je BC, maar dat faalt dus.

Ik denk dat een lijstje met translation-dirs wel zou kunnen werken, ik weet alleen niet hoe je dat qua syntax moet verwerken in de regel waar de `find` wordt uitgevoerd.

2020-08-20 08:27 UTC, boudewijn-zicht commented on messages/z.yml
> +          find vendor/zicht translations src -type f -name "*.??.yml" -exec $(defaults("php_bin", target_env, "php")) $(envs[target_env].root)$(symfony.console) --env=$(target_env) $(VERBOSE ? "--ver
Zie mijn comment, ik heb daar een stukje bash waarvan ik verwacht dat het een heel eind moet komen met wat we willen.

2020-08-20 08:30 UTC, 7ochem commented on messages/z.yml
> +          find vendor/zicht translations src -type f -name "*.??.yml" -exec $(defaults("php_bin", target_env, "php")) $(envs[target_env].root)$(symfony.console) --env=$(target_env) $(VERBOSE ? "--ver
Ik wilde ook al zo'n mooi stukje bash hier gaan commenten, maar dit zit in de z.yml en die kan niet zo goed tegen allerlei geavanceerde bash syntax. Zal dus een kwestie zijn van trial & error om te kijken wat Z wel slikt.

2020-08-20 08:36 UTC, erik-zicht commented on messages/z.yml
> +          find vendor/zicht translations src -type f -name "*.??.yml" -exec $(defaults("php_bin", target_env, "php")) $(envs[target_env].root)$(symfony.console) --env=$(target_env) $(VERBOSE ? "--ver
Ik denk dat ik een hele simpele aanpassing heb gevonden, zonder bash voodoo

2020-08-20 08:56 UTC, 7ochem commented on messages/z.yml
> +          find vendor/zicht translations src -type f -name "*.??.yml" -exec $(defaults("php_bin", target_env, "php")) $(envs[target_env].root)$(symfony.console) --env=$(target_env) $(VERBOSE ? "--ver
Dat bedoelde ik inderdaad met
> Of in een variabele in Z, dus in alle Sf4 projecten die setting aanvullen.

:smile: 

In projecten die worden geupgrade naar Sf4 heb ik geadviseerd wel alle niet-PHP zooi in sr/Zicht/Bundle/WebsiteBundle/Resources/* te laten staan. Dus in dat geval heb je wel een Sf4 project zonder translations/ dir en met translations in src/

2020-08-20 09:04 UTC, erik-zicht commented on messages/z.yml
> +          find vendor/zicht translations src -type f -name "*.??.yml" -exec $(defaults("php_bin", target_env, "php")) $(envs[target_env].root)$(symfony.console) --env=$(target_env) $(VERBOSE ? "--ver
Ok, maar dat is prima toch, je kunt het hiermee zelf beinvloeden. Of bedoel je te zeggen dat er nog iets aangepast moet worden?

2020-08-20 09:13 UTC, 7ochem commented on messages/z.yml
> +          find vendor/zicht translations src -type f -name "*.??.yml" -exec $(defaults("php_bin", target_env, "php")) $(envs[target_env].root)$(symfony.console) --env=$(target_env) $(VERBOSE ? "--ver
Nee, het is prima zo. Doe je ook nog even een PR-etje in de Cookiecutter?

2020-08-20 09:13 UTC, 7ochem approved these changes

2020-08-20 09:37 UTC, merged